#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "kokki"

input = ARGV.first

if input
  begin
    puts Kokki.flagize(input)
  rescue Kokki::InvalidInputError => e
    puts e.message
  end
else
  puts "Input not found: plase give a word to convert."
end
